---
abstract: 'a simple wrapper around Log::Dispatch'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatchouli
requires:
  Carp: 0
  Log::Dispatch: 0
  Log::Dispatch::Array: 0
  Log::Dispatch::File: 0
  Log::Dispatch::Screen: 0
  Log::Dispatch::Syslog: 0
  Params::Util: 0
  Scalar::Util: 0
  String::Flogger: 0
  Sys::Syslog: 0.16
  Test::Deep: 0
  Test::More: 0.88
  Try::Tiny: 0.04
  overload: 0
resources:
  repository: git://git.codesimply.com/Log-Dispatchouli.git
version: 1.100670
